package com.wrbug.developerhelper.constant

object ReceiverConstant {
    const val ACTION_HIERARCHY_VIEW = "ACTION_HIERARCHY_VIEW"
    const val ACTION_SET_FLOAT_BUTTON_VISIBLE = "ACTION_SET_FLOAT_BUTTON_VISIBLE"

    const val ACTION_ACCESSIBILITY_SERVICE_STATUS_CHANGED="ACTION_ACCESSIBILITY_SERVICE_STATUS_CHANGED"
}