package com.wrbug.developerhelper.constant

object ReceiverConstant {
    const val ACTION_HIERARCHY_VIEW = "ACTION_HIERARCHY_VIEW"
    const val ACTION_SET_FLOAT_VIEW_VISIBLE = "ACTION_SET_FLOAT_VIEW_VISIBLE"
    const val ACTION_SHOW_LAYOUT_INFO_VIEW = "ACTION_SHOW_LAYOUT_INFO_VIEW"
    const val ACTION_HIDE_LAYOUT_INFO_VIEW = "ACTION_HIDE_LAYOUT_INFO_VIEW"
}