package com.wrbug.developerhelper.constant

object ReceiverConstant {
    const val ACTION_HIERARCHY_VIEW = "ACTION_HIERARCHY_VIEW"
    const val ACTION_SET_FLOAT_BUTTON_VISIBLE = "ACTION_SET_FLOAT_BUTTON_VISIBLE"
    const val ACTION_ADB_WIFI_CLICKED = "ACTION_ADB_WIFI_CLICKED"
    const val ACTION_FINISH_HIERACHY_Activity = "ACTION_FINISH_HIERACHY_Activity"
    const val ACTION_ACCESSIBILITY_SERVICE_STATUS_CHANGED = "ACTION_ACCESSIBILITY_SERVICE_STATUS_CHANGED"
}